"""empty message

Revision ID: 90140506b54a
Revises: 
Create Date: 2022-04-22 01:55:50.320443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "90140506b54a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "permission",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_permission")),
        sa.UniqueConstraint("name", name=op.f("uq_permission_name")),
    )
    op.create_index(
        op.f("ix_permission_id"), "permission", ["id"], unique=True
    )
    op.create_table(
        "role",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_role")),
        sa.UniqueConstraint("name", name=op.f("uq_role_name")),
    )
    op.create_index(op.f("ix_role_id"), "role", ["id"], unique=True)
    op.create_table(
        "task",
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task")),
    )
    op.create_index(op.f("ix_task_id"), "task", ["id"], unique=True)
    op.create_table(
        "user",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("first_name", sa.String(length=255), nullable=False),
        sa.Column("last_name", sa.String(length=255), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("phone", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user")),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_index(op.f("ix_user_id"), "user", ["id"], unique=True)
    op.create_index(op.f("ix_user_phone"), "user", ["phone"], unique=True)
    op.create_index(
        op.f("ix_user_username"), "user", ["username"], unique=True
    )
    op.create_table(
        "role_permission",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("role_id", sa.BigInteger(), nullable=False),
        sa.Column("permission_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permission.id"],
            name=op.f("fk_role_permission_permission_id_permission"),
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["role.id"],
            name=op.f("fk_role_permission_role_id_role"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_role_permission")),
    )
    op.create_index(
        op.f("ix_role_permission_id"), "role_permission", ["id"], unique=True
    )
    op.create_index(
        op.f("ix_role_permission_permission_id"),
        "role_permission",
        ["permission_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_role_permission_role_id"),
        "role_permission",
        ["role_id"],
        unique=False,
    )
    op.create_table(
        "user_task",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("task_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "user_type",
            sa.Enum("assignee", "watcher", "author", name="usertasktype"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["task.id"], name=op.f("fk_user_task_task_id_task")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_user_task_user_id_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_task")),
    )
    op.create_index(op.f("ix_user_task_id"), "user_task", ["id"], unique=True)
    op.create_index(
        op.f("ix_user_task_task_id"), "user_task", ["task_id"], unique=False
    )
    op.create_index(
        op.f("ix_user_task_user_id"), "user_task", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_user_task_user_type"),
        "user_task",
        ["user_type"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_task_user_type"), table_name="user_task")
    op.drop_index(op.f("ix_user_task_user_id"), table_name="user_task")
    op.drop_index(op.f("ix_user_task_task_id"), table_name="user_task")
    op.drop_index(op.f("ix_user_task_id"), table_name="user_task")
    op.drop_table("user_task")
    op.drop_index(
        op.f("ix_role_permission_role_id"), table_name="role_permission"
    )
    op.drop_index(
        op.f("ix_role_permission_permission_id"), table_name="role_permission"
    )
    op.drop_index(op.f("ix_role_permission_id"), table_name="role_permission")
    op.drop_table("role_permission")
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.drop_index(op.f("ix_user_phone"), table_name="user")
    op.drop_index(op.f("ix_user_id"), table_name="user")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_task_id"), table_name="task")
    op.drop_table("task")
    op.drop_index(op.f("ix_role_id"), table_name="role")
    op.drop_table("role")
    op.drop_index(op.f("ix_permission_id"), table_name="permission")
    op.drop_table("permission")
    # ### end Alembic commands ###
